### PR TITLE
Use raw links

### PR DESCRIPTION
**Pull request by Araxeus**
The current examples don't work. 
It only works in this repo, anywhere else you need to link to the raw image

> **Note**
> I'm confused how does this repo have 31 stars, but the examples don't work?
> did no one test this? am I somehow missing something?

### CODE REVIEW

**Comment by Mqxx** [comment]
I don't know what the problem is... The examples work perfectly fine. You don't have to use the Raw links. If it solves the problem for you then please use the raw links.

Are the badges just not rendering properly on your end?

**Comment by Araxeus** [comment]
Please try using those links in the comments here... how can you say it's working fine? have you tried using it anywhere that isn't the readme of this repo?

here's the version currently in the readme:

> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://github.com/Mqxx/GitHub-Markdown/blob/main/blockquotes/badge/light-theme/info.svg">
>   Info
> </picture><br>
>
> Info

<details>
<summary>Code</summary>

```md
> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://github.com/Mqxx/GitHub-Markdown/blob/main/blockquotes/badge/light-theme/info.svg">
>   <img alt="Info" src="https://github.com/Mqxx/GitHub-Markdown/blob/main/blockquotes/badge/dark-theme/info.svg">
> </picture><br>
>
> Info
```

</details>

here's the raw version:

> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/info.svg">
>   Info
> </picture><br>
>
> Info

<details>
<summary>Code</summary>

```md
> <picture>
>   <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/info.svg">
>   <img alt="Info" src="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/dark-theme/info.svg">
> </picture><br>
>
> Info
```

</details>

<details>
<summary>Screenshot of this comment on my end, just in case</summary>

image

</details>

**Review by Mqxx — APPROVED** [review]

**Comment by Mqxx** [comment]
Yes it is also only for the README. GitHub gets the SVG from the original source when parsing the markdown file, so it is only displayed correctly in the READMEs.

**Comment by Mqxx** [comment]
I have merged the new code thanks for updating it correctly!

**Pull request merged**
